---
title: "Report 10 - 20195674"
author: "José Uscamayta Quispe"
date: "26/11/2021"
output: pdf_document
---

1. What is the research question of the paper?

More than a research question, the paper deals with a new way of calculating a price index that better reflects the change in consumer welfare, given that the ones that are usually used have certain biases, since they are based on prices and in certain occasions on non-comparable products that are present today and not in the past. What the paper proposes is to create the price index by means of the characteristics of the product using the Deep Learning methodology. For this purpose, the term Hedonic prices is introduced, in order to solve the problem of non-comparability of old and new products. So, under this approach it could be said that the price variation of products is determined by their own characteristics.

2. What are the strengths and weaknesses of the approach?

The strength is that it better reflects the change in welfare that people have when a certain price index varies, the weakness is that the information of the basket taken as a reference must be well structured so that the Deep Learning algorithm can recognize it. 
The paper mentions an important strength, which solves the problem of non-comparability of old and new products. Hedonic Price functions summarizes the relationship between prices and characteristics of goods sold in differentiated products. This shows that not all inflation is due to price variation, but that there is an issue of product differentiation and improvement.

3. How does this paper advance knowledge on the question, i.e., what is its contribution?

The contribution is important because as economists we want our statistical methods to reflect as closely as possible what actually happens in the market. Since you use product characteristics to better reflect the welfare change due to inflation, you need to convert text information to numerical information.

4. What would be one or two valuable and specific next steps to advance this question?

Try to improve Deep Learning methods to be able to apply these methods to products on the web where the information is not so well structured.